name: my_test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Upgrade pip
        run: python -m pip install --upgrade pip
        
      - name: Install poetry
        run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
        
      - name: Edit PATH
        run: export PATH=$PATH:$HOME/.poetry/bin
        
      - name: Check poetry version
        run: $HOME/.poetry/bin/poetry --version 
        
      - name: Install my package
        run: make install
        
      - name: Make lint
        run: make lint
      
